version: '3.8'

services:
  postgres:
    image: postgis/postgis:15-3.3
    container_name: dev-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: aniwhere
      POSTGRES_USER: satoru
      POSTGRES_PASSWORD: gozo
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
