version: '3.9'

services:
  backend:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yagubogu-backend
    ports:
      - "80:80"
    environment:
      TZ: Asia/Seoul
      JAVA_OPTS: "-XX:MaxRAMPercentage=75 -XX:+UseG1GC"
      SPRING_PROFILES_ACTIVE: dev
      SERVER_PORT: 80
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      ACCESS_TOKEN_SECRET_KEY: ${ACCESS_TOKEN_SECRET_KEY}
      REFRESH_TOKEN_SECRET_KEY: ${REFRESH_TOKEN_SECRET_KEY}
    depends_on:
      - db
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:80/actuator/health" ]
      interval: 15s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  db:
    image: mysql:8.1
    container_name: yagubogu-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: yagubogu
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    restart: unless-stopped

volumes:
  db-data:
