spring:
  datasource:
    # TODO : db 정하기
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:database;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: satoru
    password:
  h2:
    console:
      enabled: false
      path: /h2-console
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
