spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/aniwhere
    username: satoru
    password: gozo
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
