name: YaguBogu Android CI

on:
  push:
    branches: [ "dev-an" ]
    paths:
      - 'android/**'
  pull_request:
    branches: [ "dev-an" ]
    paths:
      - 'android/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
      
    defaults:
      run:
        working-directory: android

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Clean build with Gradle
      run: ./gradlew clean build

    - name: Run ktlint check
      run: ./gradlew ktlintCheck
