name: YaguBogu Backend dev-be

# 0. workflow 실행 트리거
on:
  push:
    branches: [ "dev-be" ]
    path:
      - 'backend/**'
  pull_request:
    branches: [ "dev-be" ]
    path:
      - 'backend/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run Tests
        run: ./gradlew test

      - name: Build
        run: ./gradlew build -x test
