name: Auto Close Linked Issues on PR Merge

on:
  pull_request:
    types:
      - closed

jobs:
  close_issues:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    permissions:
      issues: write

    steps:
      - name: Close issues referenced in PR body
        uses: actions/github-script@v7
        with:
          script: |
            // PR 본문 추출 (null 방지)
            const prBody = context.payload.pull_request.body || '';

            // "Closes #123", "Fixes #456", "Resolved #789" 등 패턴 매칭
            const issuePattern = /(close[sd]?|fix(e[sd])?|resolve[sd]?)\s+#(\d+)/gi;

            // 매칭 결과 배열화
            const matches = [...prBody.matchAll(issuePattern)];

            if (matches.length === 0) {
              console.log('참조된 이슈가 없습니다.');
              return;
            }

            // 중복 이슈 방지용 Set
            const closedIssues = new Set();

            // 매칭된 이슈 번호들을 반복 처리
            for (const match of matches) {
              const issueNumber = match[3];  // 정규식 3번째 그룹: 이슈 번호
              if (closedIssues.has(issueNumber)) continue; // 중복 방지
              closedIssues.add(issueNumber);

              console.log(`이슈 #${issueNumber} 닫기 시도`);

              try {
                await github.rest.issues.update({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: Number(issueNumber),
                  state: 'closed',
                });
              } catch (error) {
                // 실패 시 워크플로 중단 방지 (예: 권한 문제 등)
                console.warn(`이슈 #${issueNumber} 닫기 실패: ${error.message}`);
              }
            }
